class PythonUtilityError( Exception ):

    pass

#-- END class PythonUtilityError --#
